### ISSUE TITLE
Fly

### ISSUE THREAD

**Issue by LewBr** [AndreTheGamer/HubPE#1]
can you make a system that's make the players only at the lobby flying whit the permission please?

**Comment by xZeroMCPE** [comment]
@LewBr So like its online active at one world?

**Comment by LewBr** [comment]
Yes, i need soo much that.. (sorry english)

**Comment by xZeroMCPE** [comment]
Alright, i"ll see what i can do.

**Comment by xZeroMCPE** [comment]
Added!
